# Generated by Django 3.0.2 on 2020-02-05 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SongFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fnam', models.CharField(default='', max_length=200)),
                ('art', models.CharField(default='', max_length=100)),
                ('alb', models.CharField(default='', max_length=100)),
                ('tit', models.CharField(default='', max_length=100)),
                ('mat', models.CharField(default='', max_length=2000)),
                ('ind', models.IntegerField(default=-1)),
                ('wht', models.FloatField(default=0)),
            ],
        ),
    ]
